[package]
name = "bevy_qoi"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "~0.8", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
] }
qoi = "0.4"
anyhow = "*"

[dev-dependencies]
bevy = { version = "~0.8", default-features = true }
